// Forecast Drill-down P0 — canonical transaction-detail routing regression.
//
// Regression target: commit 9fca6dc ("unify transaction detail modal across
// Budget, License, and Device") replaced `openMemoReadOnly` with
// `openCanonicalTransactionDetailForMemo` as the active entry point for
// License and Device. These tests pin that routing and confirm the
// canonical panel itself excludes approval/audit sections (that content is
// only ever generated by history.js's Memo History path).
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { loadViews } = require('./helpers/load_views');

const { app, budget, device } = loadViews();

function lastAppendedPanel() {
  const children = global.document.body.children;
  return children[children.length - 1];
}

function softwareMemoDoc(overrides = {}) {
  return {
    memoNo: 'MEMO-ROUTE-1',
    type: 'sl',
    status: 'completed',
    project: 'AOA',
    total: 5000,
    subject: 'Software renewal',
    approvers: [{ name: 'A. Reviewer', title: 'Manager', status: 'approved' }],
    auditLog: [{ actor: 'A. Reviewer', action: 'Approved', timestamp: '2026-01-05T00:00:00Z' }],
    slItems: [{ name: 'Figma', plan: 'Org', price: 1000, months: 12, qty: 1, startMonth: '2026-01', endMonth: '2026-12' }],
    ...overrides,
  };
}

test('Forecast/Budget: openCanonicalTransactionDetailForMemo renders the canonical panel', () => {
  app.storeMemos([softwareMemoDoc()]);
  budget.openCanonicalTransactionDetailForMemo('MEMO-ROUTE-1');
  const panel = lastAppendedPanel();
  assert.equal(panel.id, 'actual-spend-record-detail');
});

test('Canonical transaction detail excludes Approval Timeline / Audit Log / approver sections', () => {
  app.storeMemos([softwareMemoDoc()]);
  budget.openCanonicalTransactionDetailForMemo('MEMO-ROUTE-1');
  const panel = lastAppendedPanel();
  assert.ok(!panel.innerHTML.includes('Approval Timeline'));
  assert.ok(!panel.innerHTML.includes('Audit Log'));
  assert.ok(!panel.innerHTML.includes('ผู้อนุมัติ'));
  // It still shows the spend-type-specific detail (proves the section isn't just hidden entirely).
  assert.ok(panel.innerHTML.includes('Figma') || panel.innerHTML.toLowerCase().includes('software'));
});

test('Device: "View Source Memo" wires to the canonical route, not the full Memo History detail', () => {
  device.storeDevices([{ id: 'dev-route-1', memoNo: 'MEMO-DEV-ROUTE', platform: 'ios', type: 'mobile', status: 'active', pbxNumber: '999' }]);
  device.openDeviceDetail('dev-route-1');
  const panel = lastAppendedPanel();
  assert.ok(panel.innerHTML.includes("openCanonicalTransactionDetailForMemo("), 'expected canonical route call in device detail HTML');
  assert.ok(!panel.innerHTML.includes('openMemoReadOnly('), 'device detail must not open the full workflow Memo History view');
});

test('Manual Entry detail also uses the canonical component (showManualEntryDetail)', () => {
  assert.equal(typeof budget.showManualEntryDetail, 'function');
});

test('License: memo-number links route through the canonical component, not openMemoReadOnly (source regression)', () => {
  // license.js's row/queue renderers are heavily coupled to live filter-UI DOM
  // elements and stored license/account data; re-exercising them here would
  // require reconstructing that whole surface for no extra fidelity over
  // reading the exact template strings that drive the onclick wiring, which
  // is what actually shipped in commit 9fca6dc. This is a deliberate,
  // documented trade-off — see the audit notes for this task.
  const licenseSource = fs.readFileSync(path.join(__dirname, '..', 'views', 'license.js'), 'utf8');
  assert.ok(licenseSource.includes("openCanonicalTransactionDetailForMemo("), 'license.js should route memo links through the canonical component');
  assert.ok(!licenseSource.includes('openMemoReadOnly('), 'license.js must not call the full workflow Memo History detail directly');
});
