begin;

-- Phase 5 schema-only bundle for the live PMO_ERP database.
--
-- Source of truth:
-- 1. docs/INTEGRATION/schema_reference/PMO_ERP_LIVE_SCHEMA.sql
-- 2. current integrated app code
-- 3. cleaned Phase 2 migration draft
--
-- This bundle is additive only. It intentionally excludes data backfills,
-- Resource / Settings / Project Code changes, duplicate memos.memo_no unique
-- indexes, and future-normalization objects.

-- ---------------------------------------------------------------------------
-- Shared approval/profile masters used by Memo approval flows.
-- ---------------------------------------------------------------------------

create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  full_name text not null,
  title text,
  name_aliases text[] not null default '{}'::text[],
  email text,
  is_approver boolean not null default false,
  can_review boolean not null default false,
  can_approve boolean not null default false,
  is_pmo boolean not null default false,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.user_profiles
  add column if not exists full_name text,
  add column if not exists title text,
  add column if not exists name_aliases text[] not null default '{}'::text[],
  add column if not exists email text,
  add column if not exists is_approver boolean not null default false,
  add column if not exists can_review boolean not null default false,
  add column if not exists can_approve boolean not null default false,
  add column if not exists is_pmo boolean not null default false,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

create table if not exists public.authority_limits (
  title text not null,
  memo_type text not null,
  limit_thb numeric(16,2) not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (title, memo_type),
  constraint authority_limits_memo_type_chk
    check (memo_type in ('sl', 'hw', 'int', 'ent', 'dep')),
  constraint authority_limits_limit_nonnegative_chk
    check (limit_thb >= 0)
);

alter table public.authority_limits
  add column if not exists limit_thb numeric(16,2) not null default 0,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

create unique index if not exists user_profiles_full_name_uidx
  on public.user_profiles (full_name)
  where nullif(btrim(full_name), '') is not null;

create unique index if not exists user_profiles_email_lower_uidx
  on public.user_profiles (lower(email))
  where email is not null and btrim(email) <> '';

create index if not exists user_profiles_is_active_idx
  on public.user_profiles (is_active);

create index if not exists user_profiles_can_review_idx
  on public.user_profiles (can_review);

create index if not exists user_profiles_can_approve_idx
  on public.user_profiles (can_approve);

create index if not exists user_profiles_is_pmo_idx
  on public.user_profiles (is_pmo);

-- ---------------------------------------------------------------------------
-- Memo workflow, detail-restore, void/delete, and financial metadata fields.
-- ---------------------------------------------------------------------------

alter table public.memos
  add column if not exists requester_profile_id bigint,
  add column if not exists current_approver_profile_id bigint,
  add column if not exists self_reviewed_at timestamp with time zone,
  add column if not exists source_memo_no text,
  add column if not exists voided_at timestamp with time zone,
  add column if not exists voided_by text,
  add column if not exists void_reason text,
  add column if not exists void_evidence_url text,
  add column if not exists deleted boolean not null default false,
  add column if not exists deleted_at timestamp with time zone,
  add column if not exists deleted_by text,
  add column if not exists delete_reason text,
  add column if not exists hw_items jsonb not null default '[]'::jsonb,
  add column if not exists hw_owner text,
  add column if not exists acct_cols jsonb not null default '[]'::jsonb,
  add column if not exists acct_rows jsonb not null default '[]'::jsonb,
  add column if not exists int_names jsonb not null default '[]'::jsonb,
  add column if not exists dep_items jsonb not null default '[]'::jsonb,
  add column if not exists currency text not null default 'THB',
  add column if not exists created_by text,
  add column if not exists updated_by text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'memos_requester_profile_fk' and conrelid = 'public.memos'::regclass) then
    alter table public.memos
      add constraint memos_requester_profile_fk
      foreign key (requester_profile_id) references public.user_profiles(id)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'memos_current_approver_profile_fk' and conrelid = 'public.memos'::regclass) then
    alter table public.memos
      add constraint memos_current_approver_profile_fk
      foreign key (current_approver_profile_id) references public.user_profiles(id)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'memos_source_memo_no_fk' and conrelid = 'public.memos'::regclass) then
    alter table public.memos
      add constraint memos_source_memo_no_fk
      foreign key (source_memo_no) references public.memos(memo_no)
      on delete set null not valid;
  end if;
end $$;

create index if not exists memos_requester_profile_id_idx
  on public.memos (requester_profile_id);

create index if not exists memos_current_approver_profile_id_idx
  on public.memos (current_approver_profile_id)
  where status in ('pending', 'pending_a2', 'pending_a3');

create index if not exists memos_budget_pool_idx
  on public.memos (budget_pool_id);

-- ---------------------------------------------------------------------------
-- Budget vs Actual app tables.
-- ---------------------------------------------------------------------------

create table if not exists public.budget_pools (
  id text primary key,
  project text,
  name text not null,
  budget numeric(16,2) not null default 0,
  year integer,
  start_month text,
  end_month text,
  memo_types jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by text,
  updated_by text,
  constraint budget_pools_budget_nonnegative_chk check (budget >= 0),
  constraint budget_pools_month_range_chk check (
    (start_month is null and end_month is null)
    or
    (start_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
      and end_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
      and start_month <= end_month)
  )
);

alter table public.budget_pools
  add column if not exists project text,
  add column if not exists name text,
  add column if not exists budget numeric(16,2) not null default 0,
  add column if not exists year integer,
  add column if not exists start_month text,
  add column if not exists end_month text,
  add column if not exists memo_types jsonb not null default '[]'::jsonb,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now(),
  add column if not exists created_by text,
  add column if not exists updated_by text;

create table if not exists public.infra_costs (
  id text primary key,
  project text,
  program text,
  monthly_cost numeric(16,2) not null default 0,
  start_month text,
  end_month text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint infra_costs_monthly_cost_nonnegative_chk check (monthly_cost >= 0),
  constraint infra_costs_month_range_chk check (
    start_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
    and end_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
    and start_month <= end_month
  )
);

alter table public.infra_costs
  add column if not exists project text,
  add column if not exists program text,
  add column if not exists monthly_cost numeric(16,2) not null default 0,
  add column if not exists start_month text,
  add column if not exists end_month text,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

create table if not exists public.budget_manual_expenses (
  id text primary key,
  entry_kind text not null default 'historical',
  reference_no text,
  project text not null,
  budget_pool_id text,
  expense_type text not null,
  description text not null,
  frequency text not null default 'one_time',
  expense_date date,
  start_month text,
  end_month text,
  quantity numeric not null default 1,
  unit_cost numeric not null default 0,
  amount numeric not null,
  vendor_program text,
  notes text,
  audit_log jsonb not null default '[]'::jsonb,
  created_by text,
  updated_by text,
  voided_at timestamp with time zone,
  voided_by text,
  void_reason text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint budget_manual_expenses_entry_kind_chk
    check (entry_kind in ('historical', 'adjustment', 'other')),
  constraint budget_manual_expenses_expense_type_chk
    check (expense_type in ('sl', 'hw', 'int', 'ent', 'dep', 'infra', 'other')),
  constraint budget_manual_expenses_frequency_chk
    check (frequency in ('one_time', 'monthly')),
  constraint budget_manual_expenses_quantity_positive_chk
    check (quantity > 0),
  constraint budget_manual_expenses_unit_cost_nonnegative_chk
    check (unit_cost >= 0),
  constraint budget_manual_expenses_amount_positive_chk
    check (amount > 0),
  constraint budget_manual_expenses_schedule_check check (
    (frequency = 'one_time' and expense_date is not null)
    or
    (frequency = 'monthly'
      and start_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
      and end_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
      and start_month <= end_month)
  )
);

alter table public.budget_manual_expenses
  add column if not exists entry_kind text not null default 'historical',
  add column if not exists reference_no text,
  add column if not exists project text,
  add column if not exists budget_pool_id text,
  add column if not exists expense_type text,
  add column if not exists description text,
  add column if not exists frequency text not null default 'one_time',
  add column if not exists expense_date date,
  add column if not exists start_month text,
  add column if not exists end_month text,
  add column if not exists quantity numeric not null default 1,
  add column if not exists unit_cost numeric not null default 0,
  add column if not exists amount numeric,
  add column if not exists vendor_program text,
  add column if not exists notes text,
  add column if not exists audit_log jsonb not null default '[]'::jsonb,
  add column if not exists created_by text,
  add column if not exists updated_by text,
  add column if not exists voided_at timestamp with time zone,
  add column if not exists voided_by text,
  add column if not exists void_reason text,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'memos_budget_pool_fk' and conrelid = 'public.memos'::regclass) then
    alter table public.memos
      add constraint memos_budget_pool_fk
      foreign key (budget_pool_id) references public.budget_pools(id)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'budget_manual_expenses_budget_pool_fk' and conrelid = 'public.budget_manual_expenses'::regclass) then
    alter table public.budget_manual_expenses
      add constraint budget_manual_expenses_budget_pool_fk
      foreign key (budget_pool_id) references public.budget_pools(id)
      on delete set null not valid;
  end if;
end $$;

create index if not exists budget_pools_project_idx
  on public.budget_pools (project);

create index if not exists budget_pools_project_name_idx
  on public.budget_pools (project, name);

create index if not exists infra_costs_project_idx
  on public.infra_costs (project);

create index if not exists budget_manual_expenses_project_date_idx
  on public.budget_manual_expenses (project, expense_date)
  where voided_at is null;

create index if not exists budget_manual_expenses_pool_idx
  on public.budget_manual_expenses (budget_pool_id)
  where voided_at is null;

create index if not exists budget_manual_expenses_reference_idx
  on public.budget_manual_expenses (reference_no)
  where reference_no is not null;

-- ---------------------------------------------------------------------------
-- License Management app table.
-- ---------------------------------------------------------------------------

create table if not exists public.licenses (
  id text primary key,
  name text,
  plan text,
  vendor text,
  seats integer not null default 1,
  price_per_month numeric(16,2) not null default 0,
  owner text,
  department text,
  project text,
  license_type text,
  purchase_date date,
  expiry date,
  billing_freq text,
  status_override text,
  memo_no text,
  note text,
  source text not null default 'manual',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint licenses_seats_positive_chk check (seats > 0),
  constraint licenses_price_per_month_nonnegative_chk check (price_per_month >= 0)
);

alter table public.licenses
  add column if not exists name text,
  add column if not exists plan text,
  add column if not exists vendor text,
  add column if not exists seats integer not null default 1,
  add column if not exists price_per_month numeric(16,2) not null default 0,
  add column if not exists owner text,
  add column if not exists department text,
  add column if not exists project text,
  add column if not exists license_type text,
  add column if not exists purchase_date date,
  add column if not exists expiry date,
  add column if not exists billing_freq text,
  add column if not exists status_override text,
  add column if not exists memo_no text,
  add column if not exists note text,
  add column if not exists source text not null default 'manual',
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'licenses_memo_no_fk' and conrelid = 'public.licenses'::regclass) then
    alter table public.licenses
      add constraint licenses_memo_no_fk
      foreign key (memo_no) references public.memos(memo_no)
      on delete set null not valid;
  end if;
end $$;

create index if not exists licenses_source_idx
  on public.licenses (source);

create index if not exists licenses_memo_no_idx
  on public.licenses (memo_no);

-- ---------------------------------------------------------------------------
-- Device Management app tables.
-- ---------------------------------------------------------------------------

create table if not exists public.purchase_orders (
  id text primary key,
  memo_no text,
  project text,
  item_name text,
  ordered_qty integer not null default 1,
  arrived_qty integer not null default 0,
  status text not null default 'ordered',
  note text,
  audit_log jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by text,
  updated_by text,
  constraint purchase_orders_ordered_qty_positive_chk check (ordered_qty > 0),
  constraint purchase_orders_arrived_qty_nonnegative_chk check (arrived_qty >= 0),
  constraint purchase_orders_arrived_qty_lte_ordered_chk check (arrived_qty <= ordered_qty)
);

alter table public.purchase_orders
  add column if not exists memo_no text,
  add column if not exists project text,
  add column if not exists item_name text,
  add column if not exists ordered_qty integer not null default 1,
  add column if not exists arrived_qty integer not null default 0,
  add column if not exists status text not null default 'ordered',
  add column if not exists note text,
  add column if not exists audit_log jsonb not null default '[]'::jsonb,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now(),
  add column if not exists created_by text,
  add column if not exists updated_by text;

create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  name text,
  brand text,
  platform text,
  type text,
  serial text,
  asset_tag text,
  pbx_number text,
  owner text,
  position text,
  assigned_date date,
  project text,
  company text,
  return_date date,
  warranty date,
  qa_owner text,
  os_version text,
  photo_url text,
  status text not null default 'not_identified',
  memo_ref text,
  purchase_order_id text,
  note text,
  source text not null default 'manual',
  deleted boolean not null default false,
  deleted_at timestamp with time zone,
  deleted_by text,
  audit_log jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by text,
  updated_by text
);

alter table public.devices
  add column if not exists name text,
  add column if not exists brand text,
  add column if not exists platform text,
  add column if not exists type text,
  add column if not exists serial text,
  add column if not exists asset_tag text,
  add column if not exists pbx_number text,
  add column if not exists owner text,
  add column if not exists position text,
  add column if not exists assigned_date date,
  add column if not exists project text,
  add column if not exists company text,
  add column if not exists return_date date,
  add column if not exists warranty date,
  add column if not exists qa_owner text,
  add column if not exists os_version text,
  add column if not exists photo_url text,
  add column if not exists status text not null default 'not_identified',
  add column if not exists memo_ref text,
  add column if not exists purchase_order_id text,
  add column if not exists note text,
  add column if not exists source text not null default 'manual',
  add column if not exists deleted boolean not null default false,
  add column if not exists deleted_at timestamp with time zone,
  add column if not exists deleted_by text,
  add column if not exists audit_log jsonb not null default '[]'::jsonb,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now(),
  add column if not exists created_by text,
  add column if not exists updated_by text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'purchase_orders_memo_no_fk' and conrelid = 'public.purchase_orders'::regclass) then
    alter table public.purchase_orders
      add constraint purchase_orders_memo_no_fk
      foreign key (memo_no) references public.memos(memo_no)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'devices_memo_ref_fk' and conrelid = 'public.devices'::regclass) then
    alter table public.devices
      add constraint devices_memo_ref_fk
      foreign key (memo_ref) references public.memos(memo_no)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'devices_purchase_order_fk' and conrelid = 'public.devices'::regclass) then
    alter table public.devices
      add constraint devices_purchase_order_fk
      foreign key (purchase_order_id) references public.purchase_orders(id)
      on delete set null not valid;
  end if;
end $$;

create index if not exists purchase_orders_memo_no_idx
  on public.purchase_orders (memo_no);

create index if not exists purchase_orders_created_at_idx
  on public.purchase_orders (created_at);

create index if not exists devices_memo_ref_idx
  on public.devices (memo_ref);

create index if not exists devices_purchase_order_idx
  on public.devices (purchase_order_id);

-- ---------------------------------------------------------------------------
-- Updated-at triggers. These use the existing PMO_ERP function when present.
-- ---------------------------------------------------------------------------

do $$
begin
  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_user_profiles_updated_at' and tgrelid = 'public.user_profiles'::regclass) then
    create trigger set_user_profiles_updated_at
      before update on public.user_profiles
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_authority_limits_updated_at' and tgrelid = 'public.authority_limits'::regclass) then
    create trigger set_authority_limits_updated_at
      before update on public.authority_limits
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_budget_pools_updated_at' and tgrelid = 'public.budget_pools'::regclass) then
    create trigger set_budget_pools_updated_at
      before update on public.budget_pools
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_infra_costs_updated_at' and tgrelid = 'public.infra_costs'::regclass) then
    create trigger set_infra_costs_updated_at
      before update on public.infra_costs
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_budget_manual_expenses_updated_at' and tgrelid = 'public.budget_manual_expenses'::regclass) then
    create trigger set_budget_manual_expenses_updated_at
      before update on public.budget_manual_expenses
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_licenses_updated_at' and tgrelid = 'public.licenses'::regclass) then
    create trigger set_licenses_updated_at
      before update on public.licenses
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_purchase_orders_updated_at' and tgrelid = 'public.purchase_orders'::regclass) then
    create trigger set_purchase_orders_updated_at
      before update on public.purchase_orders
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (select 1 from pg_trigger where tgname = 'set_devices_updated_at' and tgrelid = 'public.devices'::regclass) then
    create trigger set_devices_updated_at
      before update on public.devices
      for each row execute procedure public.set_updated_at();
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Supabase Data API access. These follow the existing PoC-compatible pattern.
-- ---------------------------------------------------------------------------

alter table public.user_profiles enable row level security;
alter table public.authority_limits enable row level security;
alter table public.budget_pools enable row level security;
alter table public.infra_costs enable row level security;
alter table public.budget_manual_expenses enable row level security;
alter table public.licenses enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.devices enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'poc_read_user_profiles') then
    create policy poc_read_user_profiles on public.user_profiles for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'poc_create_user_profiles') then
    create policy poc_create_user_profiles on public.user_profiles for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'poc_update_user_profiles') then
    create policy poc_update_user_profiles on public.user_profiles for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_limits' and policyname = 'poc_read_authority_limits') then
    create policy poc_read_authority_limits on public.authority_limits for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_limits' and policyname = 'poc_create_authority_limits') then
    create policy poc_create_authority_limits on public.authority_limits for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_limits' and policyname = 'poc_update_authority_limits') then
    create policy poc_update_authority_limits on public.authority_limits for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'budget_pools' and policyname = 'poc_read_budget_pools') then
    create policy poc_read_budget_pools on public.budget_pools for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'budget_pools' and policyname = 'poc_create_budget_pools') then
    create policy poc_create_budget_pools on public.budget_pools for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'budget_pools' and policyname = 'poc_update_budget_pools') then
    create policy poc_update_budget_pools on public.budget_pools for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'infra_costs' and policyname = 'poc_read_infra_costs') then
    create policy poc_read_infra_costs on public.infra_costs for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'infra_costs' and policyname = 'poc_create_infra_costs') then
    create policy poc_create_infra_costs on public.infra_costs for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'infra_costs' and policyname = 'poc_update_infra_costs') then
    create policy poc_update_infra_costs on public.infra_costs for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'budget_manual_expenses' and policyname = 'poc_read_budget_manual_expenses') then
    create policy poc_read_budget_manual_expenses on public.budget_manual_expenses for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'budget_manual_expenses' and policyname = 'poc_create_budget_manual_expenses') then
    create policy poc_create_budget_manual_expenses on public.budget_manual_expenses for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'budget_manual_expenses' and policyname = 'poc_update_budget_manual_expenses') then
    create policy poc_update_budget_manual_expenses on public.budget_manual_expenses for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'licenses' and policyname = 'poc_read_licenses') then
    create policy poc_read_licenses on public.licenses for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'licenses' and policyname = 'poc_create_licenses') then
    create policy poc_create_licenses on public.licenses for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'licenses' and policyname = 'poc_update_licenses') then
    create policy poc_update_licenses on public.licenses for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'purchase_orders' and policyname = 'poc_read_purchase_orders') then
    create policy poc_read_purchase_orders on public.purchase_orders for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'purchase_orders' and policyname = 'poc_create_purchase_orders') then
    create policy poc_create_purchase_orders on public.purchase_orders for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'purchase_orders' and policyname = 'poc_update_purchase_orders') then
    create policy poc_update_purchase_orders on public.purchase_orders for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'devices' and policyname = 'poc_read_devices') then
    create policy poc_read_devices on public.devices for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'devices' and policyname = 'poc_create_devices') then
    create policy poc_create_devices on public.devices for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'devices' and policyname = 'poc_update_devices') then
    create policy poc_update_devices on public.devices for update to anon, authenticated using (true) with check (true);
  end if;
end $$;

grant select, insert, update on public.user_profiles to anon, authenticated;
grant select, insert, update on public.authority_limits to anon, authenticated;
grant select, insert, update on public.budget_pools to anon, authenticated;
grant select, insert, update on public.infra_costs to anon, authenticated;
grant select, insert, update on public.budget_manual_expenses to anon, authenticated;
grant select, insert, update on public.licenses to anon, authenticated;
grant select, insert, update on public.purchase_orders to anon, authenticated;
grant select, insert, update on public.devices to anon, authenticated;

do $$
begin
  if to_regclass('public.user_profiles_id_seq') is not null then
    execute 'grant usage, select on sequence public.user_profiles_id_seq to anon, authenticated';
  end if;

  if to_regclass('public.devices_id_seq') is not null then
    execute 'grant usage, select on sequence public.devices_id_seq to anon, authenticated';
  end if;
end $$;

commit;
