begin;

-- Unified schema Phase 2: Device Management baselines.
-- Purchase orders are created by approved hardware memos and device rows are
-- created from PO arrival or manual device registry entry.

-- Hardware purchase order tracking. The id remains text to preserve the
-- reference repository's memo-number/line-item derived PO identifiers.
create table if not exists public.purchase_orders (
  id text primary key,
  memo_no text,
  project text,
  organization_project_id text references public.organization_projects(id) on delete set null,
  item_name text,
  ordered_qty integer not null default 1,
  arrived_qty integer not null default 0,
  status text not null default 'ordered',
  note text,
  audit_log jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text,
  constraint purchase_orders_ordered_qty_positive_chk check (ordered_qty > 0),
  constraint purchase_orders_arrived_qty_nonnegative_chk check (arrived_qty >= 0),
  constraint purchase_orders_arrived_qty_lte_ordered_chk check (arrived_qty <= ordered_qty)
);

alter table public.purchase_orders
  add column if not exists memo_no text,
  add column if not exists project text,
  add column if not exists organization_project_id text,
  add column if not exists item_name text,
  add column if not exists ordered_qty integer not null default 1,
  add column if not exists arrived_qty integer not null default 0,
  add column if not exists status text not null default 'ordered',
  add column if not exists note text,
  add column if not exists audit_log jsonb not null default '[]'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by text,
  add column if not exists updated_by text;

-- Device registry. Supabase rows use bigint identity while local fallback
-- device IDs remain application/cache concerns outside this table.
create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  name text,
  brand text,
  platform text,
  type text,
  serial text,
  asset_tag text,
  pbx_number text,
  owner text,
  owner_profile_id bigint references public.user_profiles(id) on delete set null,
  position text,
  assigned_date date,
  project text,
  organization_project_id text references public.organization_projects(id) on delete set null,
  company text,
  return_date date,
  warranty date,
  qa_owner text,
  os_version text,
  photo_url text,
  status text not null default 'not_identified',
  memo_ref text,
  purchase_order_id text references public.purchase_orders(id) on delete set null,
  note text,
  source text not null default 'manual',
  deleted boolean not null default false,
  deleted_at timestamptz,
  deleted_by text,
  audit_log jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text
);

alter table public.devices
  add column if not exists name text,
  add column if not exists brand text,
  add column if not exists platform text,
  add column if not exists type text,
  add column if not exists serial text,
  add column if not exists asset_tag text,
  add column if not exists pbx_number text,
  add column if not exists owner text,
  add column if not exists owner_profile_id bigint,
  add column if not exists position text,
  add column if not exists assigned_date date,
  add column if not exists project text,
  add column if not exists organization_project_id text,
  add column if not exists company text,
  add column if not exists return_date date,
  add column if not exists warranty date,
  add column if not exists qa_owner text,
  add column if not exists os_version text,
  add column if not exists photo_url text,
  add column if not exists status text not null default 'not_identified',
  add column if not exists memo_ref text,
  add column if not exists purchase_order_id text,
  add column if not exists note text,
  add column if not exists source text not null default 'manual',
  add column if not exists deleted boolean not null default false,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text,
  add column if not exists audit_log jsonb not null default '[]'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by text,
  add column if not exists updated_by text;

-- Device and PO constraints/FKs are guarded so partial existing tables can be
-- aligned without renaming, dropping, or rewriting data.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'purchase_orders_memo_no_fk' and conrelid = 'public.purchase_orders'::regclass) then
    alter table public.purchase_orders
      add constraint purchase_orders_memo_no_fk
      foreign key (memo_no) references public.memos(memo_no)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'purchase_orders_organization_project_fk' and conrelid = 'public.purchase_orders'::regclass) then
    alter table public.purchase_orders
      add constraint purchase_orders_organization_project_fk
      foreign key (organization_project_id) references public.organization_projects(id)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'purchase_orders_ordered_qty_positive_chk' and conrelid = 'public.purchase_orders'::regclass) then
    alter table public.purchase_orders
      add constraint purchase_orders_ordered_qty_positive_chk check (ordered_qty > 0) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'purchase_orders_arrived_qty_nonnegative_chk' and conrelid = 'public.purchase_orders'::regclass) then
    alter table public.purchase_orders
      add constraint purchase_orders_arrived_qty_nonnegative_chk check (arrived_qty >= 0) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'purchase_orders_arrived_qty_lte_ordered_chk' and conrelid = 'public.purchase_orders'::regclass) then
    alter table public.purchase_orders
      add constraint purchase_orders_arrived_qty_lte_ordered_chk check (arrived_qty <= ordered_qty) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'devices_owner_profile_fk' and conrelid = 'public.devices'::regclass) then
    alter table public.devices
      add constraint devices_owner_profile_fk
      foreign key (owner_profile_id) references public.user_profiles(id)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'devices_organization_project_fk' and conrelid = 'public.devices'::regclass) then
    alter table public.devices
      add constraint devices_organization_project_fk
      foreign key (organization_project_id) references public.organization_projects(id)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'devices_memo_ref_fk' and conrelid = 'public.devices'::regclass) then
    alter table public.devices
      add constraint devices_memo_ref_fk
      foreign key (memo_ref) references public.memos(memo_no)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'devices_purchase_order_fk' and conrelid = 'public.devices'::regclass) then
    alter table public.devices
      add constraint devices_purchase_order_fk
      foreign key (purchase_order_id) references public.purchase_orders(id)
      on delete set null not valid;
  end if;
end $$;

-- Indexes for common device/PO filters and relationship lookups.
create index if not exists purchase_orders_memo_no_idx
  on public.purchase_orders (memo_no);

create index if not exists purchase_orders_organization_project_idx
  on public.purchase_orders (organization_project_id);

create index if not exists purchase_orders_status_idx
  on public.purchase_orders (status);

create index if not exists purchase_orders_created_at_idx
  on public.purchase_orders (created_at);

create index if not exists devices_organization_project_idx
  on public.devices (organization_project_id);

create index if not exists devices_owner_profile_idx
  on public.devices (owner_profile_id);

create index if not exists devices_memo_ref_idx
  on public.devices (memo_ref);

create index if not exists devices_purchase_order_idx
  on public.devices (purchase_order_id);

create index if not exists devices_status_idx
  on public.devices (status);

create index if not exists devices_deleted_idx
  on public.devices (deleted);

create index if not exists devices_serial_idx
  on public.devices (serial)
  where serial is not null and btrim(serial) <> '';

create index if not exists devices_asset_tag_idx
  on public.devices (asset_tag)
  where asset_tag is not null and btrim(asset_tag) <> '';

-- Updated-at triggers for device module tables.
do $$
begin
  if to_regproc('public.set_updated_at()') is not null
     and not exists (
       select 1 from pg_trigger
       where tgname = 'set_purchase_orders_updated_at'
         and tgrelid = 'public.purchase_orders'::regclass
     ) then
    create trigger set_purchase_orders_updated_at
      before update on public.purchase_orders
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (
       select 1 from pg_trigger
       where tgname = 'set_devices_updated_at'
         and tgrelid = 'public.devices'::regclass
     ) then
    create trigger set_devices_updated_at
      before update on public.devices
      for each row execute procedure public.set_updated_at();
  end if;
end $$;

-- PoC-compatible RLS and grants for device module tables.
alter table public.purchase_orders enable row level security;
alter table public.devices enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'purchase_orders' and policyname = 'poc_read_purchase_orders') then
    create policy poc_read_purchase_orders on public.purchase_orders for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'purchase_orders' and policyname = 'poc_create_purchase_orders') then
    create policy poc_create_purchase_orders on public.purchase_orders for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'purchase_orders' and policyname = 'poc_update_purchase_orders') then
    create policy poc_update_purchase_orders on public.purchase_orders for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'devices' and policyname = 'poc_read_devices') then
    create policy poc_read_devices on public.devices for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'devices' and policyname = 'poc_create_devices') then
    create policy poc_create_devices on public.devices for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'devices' and policyname = 'poc_update_devices') then
    create policy poc_update_devices on public.devices for update to anon, authenticated using (true) with check (true);
  end if;
end $$;

grant select, insert, update on public.purchase_orders to anon, authenticated;
grant select, insert, update on public.devices to anon, authenticated;

do $$
begin
  if to_regclass('public.devices_id_seq') is not null then
    execute 'grant usage, select on sequence public.devices_id_seq to anon, authenticated';
  end if;
end $$;

commit;
