begin;

-- Batch 1: additive schema for configurable approval authority, closing text,
-- profile defaults, and profile-keyed signatures. Keep every legacy string
-- field/table path available during the migration period.

create table if not exists public.authority_titles (
  id bigint generated by default as identity primary key,
  title_th text not null,
  title_en text,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint authority_titles_title_th_not_blank_chk check (btrim(title_th) <> '')
);

alter table public.authority_titles
  add column if not exists title_th text,
  add column if not exists title_en text,
  add column if not exists sort_order integer not null default 100,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

create unique index if not exists authority_titles_title_th_uidx
  on public.authority_titles (lower(btrim(title_th)))
  where btrim(title_th) <> '';

create index if not exists authority_titles_active_sort_idx
  on public.authority_titles (is_active, sort_order, title_th);

alter table public.authority_limits
  add column if not exists authority_title_id bigint,
  add column if not exists is_unlimited boolean not null default false;

do $$
begin
  if to_regclass('public.authority_limits') is not null
     and not exists (
       select 1
       from pg_constraint
       where conname = 'authority_limits_authority_title_id_fkey'
         and conrelid = 'public.authority_limits'::regclass
     ) then
    alter table public.authority_limits
      add constraint authority_limits_authority_title_id_fkey
      foreign key (authority_title_id)
      references public.authority_titles(id)
      on delete restrict;
  end if;
end $$;

create unique index if not exists authority_limits_title_id_memo_type_uidx
  on public.authority_limits (authority_title_id, memo_type)
  where authority_title_id is not null;

create index if not exists authority_limits_title_id_idx
  on public.authority_limits (authority_title_id);

alter table public.user_profiles
  add column if not exists default_authority_title_id bigint,
  add column if not exists signature_data_url text;

do $$
begin
  if to_regclass('public.user_profiles') is not null
     and not exists (
       select 1
       from pg_constraint
       where conname = 'user_profiles_default_authority_title_id_fkey'
         and conrelid = 'public.user_profiles'::regclass
     ) then
    alter table public.user_profiles
      add constraint user_profiles_default_authority_title_id_fkey
      foreign key (default_authority_title_id)
      references public.authority_titles(id)
      on delete set null;
  end if;
end $$;

create index if not exists user_profiles_default_authority_title_id_idx
  on public.user_profiles (default_authority_title_id);

create table if not exists public.memo_closing_templates (
  memo_type text primary key,
  policy_ref text,
  has_authority_clause boolean not null default true,
  template_th text not null,
  supported_placeholders text[] not null default '{}'::text[],
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint memo_closing_templates_memo_type_chk
    check (memo_type in ('sl', 'hw', 'int', 'ent', 'dep')),
  constraint memo_closing_templates_template_th_not_blank_chk
    check (btrim(template_th) <> '')
);

alter table public.memo_closing_templates
  add column if not exists policy_ref text,
  add column if not exists has_authority_clause boolean not null default true,
  add column if not exists template_th text,
  add column if not exists supported_placeholders text[] not null default '{}'::text[],
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

create index if not exists memo_closing_templates_active_idx
  on public.memo_closing_templates (is_active, memo_type);

insert into public.authority_titles (title_th, title_en, sort_order, is_active)
select seed.title_th, seed.title_en, seed.sort_order, true
from (
  values
    ('ประธานเจ้าหน้าที่บริหาร', 'Chief Executive Officer', 10),
    ('ประธานเจ้าหน้าที่สายการเงิน (CFO)', 'Chief Financial Officer', 20),
    ('ผู้อำนวยการ (Team Director)', 'Team Director', 30),
    ('ผู้อำนวยการโครงการ', 'Project Director', 40),
    ('Senior Manager / Manager', 'Senior Manager / Manager', 50),
    ('Team Leader', 'Team Leader', 60)
) as seed(title_th, title_en, sort_order)
where not exists (
  select 1
  from public.authority_titles at
  where lower(btrim(at.title_th)) = lower(btrim(seed.title_th))
);

update public.authority_titles at
set
  title_en = coalesce(nullif(btrim(at.title_en), ''), seed.title_en),
  sort_order = least(at.sort_order, seed.sort_order),
  updated_at = now()
from (
  values
    ('ประธานเจ้าหน้าที่บริหาร', 'Chief Executive Officer', 10),
    ('ประธานเจ้าหน้าที่สายการเงิน (CFO)', 'Chief Financial Officer', 20),
    ('ผู้อำนวยการ (Team Director)', 'Team Director', 30),
    ('ผู้อำนวยการโครงการ', 'Project Director', 40),
    ('Senior Manager / Manager', 'Senior Manager / Manager', 50),
    ('Team Leader', 'Team Leader', 60)
) as seed(title_th, title_en, sort_order)
where lower(btrim(at.title_th)) = lower(btrim(seed.title_th));

insert into public.authority_titles (title_th, title_en, sort_order, is_active)
select distinct btrim(al.title), null, 1000, true
from public.authority_limits al
where nullif(btrim(coalesce(al.title, '')), '') is not null
  and not exists (
    select 1
    from public.authority_titles at
    where lower(btrim(at.title_th)) = lower(btrim(al.title))
  );

update public.authority_limits al
set authority_title_id = at.id
from public.authority_titles at
where al.authority_title_id is null
  and lower(btrim(al.title)) = lower(btrim(at.title_th));

update public.user_profiles up
set default_authority_title_id = at.id
from public.authority_titles at
where up.default_authority_title_id is null
  and nullif(btrim(coalesce(up.title, '')), '') is not null
  and lower(btrim(up.title)) = lower(btrim(at.title_th));

insert into public.authority_limits (title, authority_title_id, memo_type, limit_thb, is_unlimited)
select at.title_th, at.id, seed.memo_type, seed.limit_thb, false
from public.authority_titles at
join (
  values
    ('ประธานเจ้าหน้าที่บริหาร', 'sl', 2000000::numeric), ('ประธานเจ้าหน้าที่บริหาร', 'hw', 2000000::numeric), ('ประธานเจ้าหน้าที่บริหาร', 'int', 0::numeric), ('ประธานเจ้าหน้าที่บริหาร', 'ent', 150000::numeric), ('ประธานเจ้าหน้าที่บริหาร', 'dep', 2000000::numeric),
    ('ประธานเจ้าหน้าที่สายการเงิน (CFO)', 'sl', 1000000::numeric), ('ประธานเจ้าหน้าที่สายการเงิน (CFO)', 'hw', 500000::numeric), ('ประธานเจ้าหน้าที่สายการเงิน (CFO)', 'int', 0::numeric), ('ประธานเจ้าหน้าที่สายการเงิน (CFO)', 'ent', 50000::numeric), ('ประธานเจ้าหน้าที่สายการเงิน (CFO)', 'dep', 500000::numeric),
    ('ผู้อำนวยการ (Team Director)', 'sl', 500000::numeric), ('ผู้อำนวยการ (Team Director)', 'hw', 500000::numeric), ('ผู้อำนวยการ (Team Director)', 'int', 0::numeric), ('ผู้อำนวยการ (Team Director)', 'ent', 50000::numeric), ('ผู้อำนวยการ (Team Director)', 'dep', 500000::numeric),
    ('ผู้อำนวยการโครงการ', 'sl', 500000::numeric), ('ผู้อำนวยการโครงการ', 'hw', 500000::numeric), ('ผู้อำนวยการโครงการ', 'int', 0::numeric), ('ผู้อำนวยการโครงการ', 'ent', 50000::numeric), ('ผู้อำนวยการโครงการ', 'dep', 500000::numeric),
    ('Senior Manager / Manager', 'sl', 50000::numeric), ('Senior Manager / Manager', 'hw', 50000::numeric), ('Senior Manager / Manager', 'int', 0::numeric), ('Senior Manager / Manager', 'ent', 10000::numeric), ('Senior Manager / Manager', 'dep', 50000::numeric),
    ('Team Leader', 'sl', 30000::numeric), ('Team Leader', 'hw', 30000::numeric), ('Team Leader', 'int', 0::numeric), ('Team Leader', 'ent', 5000::numeric), ('Team Leader', 'dep', 30000::numeric)
) as seed(title_th, memo_type, limit_thb)
  on lower(btrim(seed.title_th)) = lower(btrim(at.title_th))
on conflict (title, memo_type) do update
set
  authority_title_id = coalesce(public.authority_limits.authority_title_id, excluded.authority_title_id),
  is_unlimited = coalesce(public.authority_limits.is_unlimited, false),
  updated_at = now();

insert into public.memo_closing_templates
  (memo_type, policy_ref, has_authority_clause, template_th, supported_placeholders, is_active)
values
  ('sl', 'คู่มืออำนาจอนุมัติ พ.ศ. 2566 ข้อ 3.2 การชำระเงินที่มี (การตั้งงบประมาณไว้) หมวดการชำระค่าบริการ', true,
   'ในการนี้จึงขอให้ท่านโปรดพิจารณาอนุมัติงบประมาณสำหรับค่าใช้จ่ายดังกล่าว รวมเป็นจำนวนเงินไม่เกิน {{amount}} {{seat_count}} {{duration_months}} อ้างอิงอำนาจอนุมัติจาก{{policy_ref}} ซึ่งให้อำนาจแก่{{authority_title_th}}{{authority_limit}}',
   array['amount','amount_text','project_name','seat_count','duration_months','authority_title_th','authority_limit','policy_ref'], true),
  ('hw', 'คู่มืออำนาจอนุมัติ พ.ศ. 2566 ข้อ 3.2 การชำระเงินที่มี (การตั้งงบประมาณไว้) หมวดการชำระเงินค่าสวัสดิการพนักงาน', true,
   'จึงขอความกรุณาโปรดพิจารณาอนุมัติค่าใช้จ่ายสำหรับรายการจัดซื้อข้างต้น ในวงเงิน {{amount}} อ้างอิงอำนาจอนุมัติจาก{{policy_ref}} ซึ่งให้อำนาจแก่{{authority_title_th}}{{authority_limit}}',
   array['amount','amount_text','project_name','authority_title_th','authority_limit','policy_ref'], true),
  ('int', null, false,
   'ในการนี้จึงขอให้ท่านโปรดพิจารณาอนุมัติงบประมาณสำหรับค่ากิจกรรมทีม {{project_name}} เพื่อใช้จัดกิจกรรมดังกล่าว เป็นวงเงินจำนวนไม่เกิน {{amount}}',
   array['amount','amount_text','project_name'], true),
  ('ent', 'คู่มืออำนาจอนุมัติ พ.ศ. 2564 ข้อ 3.2 หมวดค่าเลี้ยงรับรอง', true,
   'ในการนี้จึงขอให้ท่านโปรดพิจารณาอนุมัติงบประมาณค่ารับรองลูกค้าจาก {{project_name}} ในช่วงเวลาดังกล่าว อ้างอิงอำนาจอนุมัติจาก{{policy_ref}} {{authority_limit}} ซึ่งให้อำนาจแก่{{authority_title_th}}ในการอนุมัติงบประมาณ',
   array['amount','amount_text','project_name','authority_title_th','authority_limit','policy_ref'], true),
  ('dep', 'คู่มืออำนาจอนุมัติ พ.ศ. 2566 ข้อ 3.2 การชำระเงินที่มี (การตั้งงบประมาณไว้) หมวดการชำระเงินค่าสวัสดิการพนักงาน', true,
   'จึงขอความอนุเคราะห์อนุมัติการจัดซื้อสำหรับรายการจัดซื้อข้างต้น ในวงเงิน {{amount}} อ้างอิงอำนาจอนุมัติจาก{{policy_ref}} ซึ่งให้อำนาจแก่{{authority_title_th}}{{authority_limit}}',
   array['amount','amount_text','project_name','authority_title_th','authority_limit','policy_ref'], true)
on conflict (memo_type) do nothing;

drop trigger if exists set_authority_titles_updated_at on public.authority_titles;
create trigger set_authority_titles_updated_at before update on public.authority_titles
for each row execute function public.set_updated_at();

drop trigger if exists set_memo_closing_templates_updated_at on public.memo_closing_templates;
create trigger set_memo_closing_templates_updated_at before update on public.memo_closing_templates
for each row execute function public.set_updated_at();

alter table public.authority_titles enable row level security;
alter table public.memo_closing_templates enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_titles' and policyname = 'poc_read_authority_titles') then
    create policy poc_read_authority_titles on public.authority_titles for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_titles' and policyname = 'poc_create_authority_titles') then
    create policy poc_create_authority_titles on public.authority_titles for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_titles' and policyname = 'poc_update_authority_titles') then
    create policy poc_update_authority_titles on public.authority_titles for update to anon, authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'memo_closing_templates' and policyname = 'poc_read_memo_closing_templates') then
    create policy poc_read_memo_closing_templates on public.memo_closing_templates for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'memo_closing_templates' and policyname = 'poc_create_memo_closing_templates') then
    create policy poc_create_memo_closing_templates on public.memo_closing_templates for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'memo_closing_templates' and policyname = 'poc_update_memo_closing_templates') then
    create policy poc_update_memo_closing_templates on public.memo_closing_templates for update to anon, authenticated using (true) with check (true);
  end if;
end $$;

grant select, insert, update on public.authority_titles to anon, authenticated;
grant select, insert, update on public.memo_closing_templates to anon, authenticated;

do $$
begin
  if to_regclass('public.authority_titles_id_seq') is not null then
    execute 'grant usage, select on sequence public.authority_titles_id_seq to anon, authenticated';
  end if;
end $$;

commit;
