begin;

-- Unified schema Phase 2: shared master baselines.
-- This migration is additive only and prepares tables required by memo,
-- approval, user assignment, device ownership, resource, and settings flows.

-- Project master baseline used across Memo, Budget vs Actual, License, Device,
-- Resource Management, and Settings. A later PMO_ERP migration also creates
-- this table with compatible columns; this early baseline makes FK ordering
-- safe for the unified schema.
create table if not exists public.organization_projects (
  id text primary key,
  code text not null,
  name text not null,
  status text not null default 'active',
  owner text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint organization_projects_status_chk
    check (status in ('active', 'inactive', 'archived'))
);

alter table public.organization_projects
  add column if not exists code text,
  add column if not exists name text,
  add column if not exists status text not null default 'active',
  add column if not exists owner text,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- User/profile master baseline shared by memo approval, license assignments,
-- device ownership, resource assignment, PMO review, and settings.
create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  full_name text not null,
  title text,
  name_aliases text[] not null default '{}'::text[],
  email text,
  is_approver boolean not null default false,
  can_review boolean not null default false,
  can_approve boolean not null default false,
  is_pmo boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles
  add column if not exists full_name text,
  add column if not exists title text,
  add column if not exists name_aliases text[] not null default '{}'::text[],
  add column if not exists email text,
  add column if not exists is_approver boolean not null default false,
  add column if not exists can_review boolean not null default false,
  add column if not exists can_approve boolean not null default false,
  add column if not exists is_pmo boolean not null default false,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- Authority limits baseline keyed by title and memo type because existing
-- settings workflows upsert with on_conflict=title,memo_type.
create table if not exists public.authority_limits (
  title text not null,
  memo_type text not null,
  limit_thb numeric(16,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (title, memo_type),
  constraint authority_limits_memo_type_chk
    check (memo_type in ('sl', 'hw', 'int', 'ent', 'dep')),
  constraint authority_limits_limit_nonnegative_chk
    check (limit_thb >= 0)
);

alter table public.authority_limits
  add column if not exists limit_thb numeric(16,2) not null default 0,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- Shared master indexes for lookup, status filtering, and duplicate prevention.
create unique index if not exists organization_projects_code_uidx
  on public.organization_projects (lower(code));

create index if not exists organization_projects_status_idx
  on public.organization_projects (status);

create unique index if not exists user_profiles_full_name_uidx
  on public.user_profiles (full_name)
  where nullif(btrim(full_name), '') is not null;

create unique index if not exists user_profiles_email_lower_uidx
  on public.user_profiles (lower(email))
  where email is not null and btrim(email) <> '';

create index if not exists user_profiles_is_active_idx
  on public.user_profiles (is_active);

create index if not exists user_profiles_can_review_idx
  on public.user_profiles (can_review);

create index if not exists user_profiles_can_approve_idx
  on public.user_profiles (can_approve);

create index if not exists user_profiles_is_pmo_idx
  on public.user_profiles (is_pmo);

create unique index if not exists authority_limits_title_memo_type_uidx
  on public.authority_limits (title, memo_type);

-- Updated-at triggers use the existing repository function and are created
-- only when absent to keep this migration forward-only.
do $$
begin
  if to_regproc('public.set_updated_at()') is not null
     and not exists (
       select 1 from pg_trigger
       where tgname = 'set_organization_projects_updated_at'
         and tgrelid = 'public.organization_projects'::regclass
     ) then
    create trigger set_organization_projects_updated_at
      before update on public.organization_projects
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (
       select 1 from pg_trigger
       where tgname = 'set_user_profiles_updated_at'
         and tgrelid = 'public.user_profiles'::regclass
     ) then
    create trigger set_user_profiles_updated_at
      before update on public.user_profiles
      for each row execute procedure public.set_updated_at();
  end if;

  if to_regproc('public.set_updated_at()') is not null
     and not exists (
       select 1 from pg_trigger
       where tgname = 'set_authority_limits_updated_at'
         and tgrelid = 'public.authority_limits'::regclass
     ) then
    create trigger set_authority_limits_updated_at
      before update on public.authority_limits
      for each row execute procedure public.set_updated_at();
  end if;
end $$;

-- PoC-compatible RLS follows the existing PMO_ERP pattern without allowing
-- deletes. Production role hardening remains a later phase.
alter table public.organization_projects enable row level security;
alter table public.user_profiles enable row level security;
alter table public.authority_limits enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'organization_projects' and policyname = 'poc_read_organization_projects') then
    create policy poc_read_organization_projects on public.organization_projects for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'organization_projects' and policyname = 'poc_create_organization_projects') then
    create policy poc_create_organization_projects on public.organization_projects for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'organization_projects' and policyname = 'poc_update_organization_projects') then
    create policy poc_update_organization_projects on public.organization_projects for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'poc_read_user_profiles') then
    create policy poc_read_user_profiles on public.user_profiles for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'poc_create_user_profiles') then
    create policy poc_create_user_profiles on public.user_profiles for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'poc_update_user_profiles') then
    create policy poc_update_user_profiles on public.user_profiles for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_limits' and policyname = 'poc_read_authority_limits') then
    create policy poc_read_authority_limits on public.authority_limits for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_limits' and policyname = 'poc_create_authority_limits') then
    create policy poc_create_authority_limits on public.authority_limits for insert to anon, authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'authority_limits' and policyname = 'poc_update_authority_limits') then
    create policy poc_update_authority_limits on public.authority_limits for update to anon, authenticated using (true) with check (true);
  end if;
end $$;

grant select, insert, update on public.organization_projects to anon, authenticated;
grant select, insert, update on public.user_profiles to anon, authenticated;
grant select, insert, update on public.authority_limits to anon, authenticated;

do $$
begin
  if to_regclass('public.user_profiles_id_seq') is not null then
    execute 'grant usage, select on sequence public.user_profiles_id_seq to anon, authenticated';
  end if;
end $$;

commit;
