-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.memos (
  id text NOT NULL,
  memo_no text NOT NULL UNIQUE,
  type text,
  type_label text,
  status text NOT NULL DEFAULT 'pending'::text,
  project text,
  subject text,
  reason text,
  to text,
  date date,
  total numeric NOT NULL DEFAULT 0,
  amount_words text,
  requester_name text,
  requester_title text,
  reviewer_name text,
  reviewer_title text,
  reviewer_date date,
  approver_name text,
  approver_title text,
  approver_date date,
  approved_by text,
  rejected_by text,
  approval_note text,
  rejection_reason text,
  fx_rate numeric,
  sections jsonb NOT NULL DEFAULT '[]'::jsonb,
  audit_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  submitted_at timestamp with time zone,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  approval_chain jsonb NOT NULL DEFAULT '[]'::jsonb,
  approval_evidence_url text,
  approvers jsonb NOT NULL DEFAULT '[]'::jsonb,
  budget_pool_id text,
  budget_source text,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  cancelled_by text,
  dep_emp_count integer,
  dep_end date,
  dep_location text,
  dep_start date,
  ent_client text,
  ent_date date,
  ent_people integer,
  ent_place text,
  ent_time text,
  int_activity text,
  int_date date,
  int_headcount integer,
  int_pp numeric,
  pmo_evidence_url text,
  pmo_override_by text,
  pmo_override_note text,
  sl_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT memos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resource_requests (
  id text NOT NULL,
  resource_team text,
  project text,
  position text,
  level text,
  hc integer NOT NULL DEFAULT 1,
  hiring_type text,
  start_date date,
  end_date date,
  request_date date,
  resolved_date date,
  remark text,
  status text NOT NULL DEFAULT 'pending'::text,
  requester_name text,
  transfer_from text,
  project_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  activity_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  hiring_type_other text,
  level_other text,
  project_other text,
  resource_team_other text,
  resource_name text,
  employee_code text,
  primary_project_code text,
  allocation_percent integer CHECK (allocation_percent IS NULL OR allocation_percent >= 1 AND allocation_percent <= 100) NOT VALI),
  onboard_date date,
  offboard_date date,
  resource_name_th text,
  resource_name_en text,
  CONSTRAINT resource_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.settings (
  id text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_code_master (
  id text NOT NULL,
  no text,
  project text NOT NULL,
  type text,
  project_code text NOT NULL UNIQUE,
  start_date date,
  end_date date,
  status text NOT NULL DEFAULT 'Active'::text,
  pm_owner text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_code_master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resource_project_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resource_request_id text NOT NULL,
  project_code_id text,
  project text NOT NULL,
  project_code text NOT NULL,
  allocation_percent integer NOT NULL DEFAULT 100 CHECK (allocation_percent >= 1 AND allocation_percent <= 100),
  supervisor text,
  start_date date,
  end_date date,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resource_project_codes_pkey PRIMARY KEY (id),
  CONSTRAINT resource_project_codes_resource_request_id_fkey FOREIGN KEY (resource_request_id) REFERENCES public.resource_requests(id),
  CONSTRAINT resource_project_codes_project_code_id_fkey FOREIGN KEY (project_code_id) REFERENCES public.project_code_master(id)
);
