-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.memos (
  id text NOT NULL,
  memo_no text NOT NULL UNIQUE,
  type text,
  type_label text,
  status text DEFAULT 'pending'::text,
  project text,
  subject text,
  reason text,
  to text,
  date text,
  total numeric DEFAULT 0,
  amount_words text,
  requester_name text,
  requester_title text,
  reviewer_name text,
  reviewer_title text,
  reviewer_date text,
  approver_name text,
  approver_title text,
  approver_date text,
  approved_by text,
  rejected_by text,
  approval_note text,
  rejection_reason text,
  fx_rate numeric,
  sections jsonb DEFAULT '[]'::jsonb,
  audit_log jsonb DEFAULT '[]'::jsonb,
  approval_chain jsonb,
  submitted_at timestamp with time zone,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sl_items jsonb DEFAULT '[]'::jsonb,
  budget_source text,
  approvers jsonb DEFAULT '[]'::jsonb,
  pmo_override_note text,
  pmo_override_by text,
  ent_client text,
  ent_date text,
  ent_time text,
  ent_place text,
  ent_people text,
  cancelled_at timestamp with time zone,
  cancelled_by text,
  cancellation_reason text,
  pmo_evidence_url text,
  approval_evidence_url text,
  int_activity text,
  int_date text,
  int_headcount integer,
  int_pp numeric,
  dep_location text,
  dep_start text,
  dep_end text,
  dep_emp_count integer,
  budget_pool_id text,
  resubmitted_at timestamp with time zone,
  resubmitted_by text,
  requester_profile_id bigint,
  current_approver_profile_id bigint,
  self_reviewed_at timestamp with time zone,
  source_memo_no text,
  voided_at timestamp with time zone,
  voided_by text,
  void_reason text,
  void_evidence_url text,
  deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by text,
  delete_reason text,
  hw_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  hw_owner text,
  acct_cols jsonb NOT NULL DEFAULT '[]'::jsonb,
  acct_rows jsonb NOT NULL DEFAULT '[]'::jsonb,
  int_names jsonb NOT NULL DEFAULT '[]'::jsonb,
  dep_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  currency text NOT NULL DEFAULT 'THB'::text,
  created_by text,
  updated_by text,
  CONSTRAINT memos_pkey PRIMARY KEY (id),
  CONSTRAINT memos_requester_profile_id_fkey FOREIGN KEY (requester_profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT memos_current_approver_profile_id_fkey FOREIGN KEY (current_approver_profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT memos_source_memo_no_fkey FOREIGN KEY (source_memo_no) REFERENCES public.memos(memo_no)
);
CREATE TABLE public.licenses (
  id text NOT NULL,
  name text NOT NULL,
  vendor text,
  seats integer DEFAULT 1,
  price_per_month numeric DEFAULT 0,
  owner text,
  department text,
  project text,
  license_type text DEFAULT 'subscription'::text,
  purchase_date text,
  expiry timestamp with time zone,
  billing_freq text DEFAULT 'monthly'::text,
  status_override text,
  memo_no text,
  note text,
  source text DEFAULT 'manual'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan text,
  CONSTRAINT licenses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.devices (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  brand text,
  platform text DEFAULT 'other'::text,
  type text DEFAULT 'other'::text,
  serial text,
  asset_tag text,
  owner text,
  assigned_date text,
  project text,
  company text,
  return_date text,
  warranty text,
  condition text DEFAULT 'good'::text,
  status text DEFAULT 'not_identified'::text,
  memo_ref text,
  note text,
  source text DEFAULT 'manual'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pbx_number text,
  position text,
  qa_owner text,
  os_version text,
  photo_url text,
  created_by text,
  updated_by text,
  deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by text,
  audit_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT devices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.settings (
  id text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resource_requests (
  id text NOT NULL,
  resource_team text NOT NULL,
  project text NOT NULL,
  position text NOT NULL,
  level text NOT NULL,
  hc integer NOT NULL DEFAULT 1,
  hiring_type text NOT NULL,
  start_date text,
  end_date text,
  request_date text NOT NULL,
  resolved_date text,
  remark text,
  status text NOT NULL DEFAULT 'pending'::text,
  requester_name text,
  transfer_from text,
  activity_log jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resource_team_other text,
  project_other text,
  level_other text,
  hiring_type_other text,
  CONSTRAINT resource_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.infra_costs (
  id text NOT NULL,
  project text NOT NULL,
  program text NOT NULL,
  monthly_cost numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  start_month text,
  end_month text,
  CONSTRAINT infra_costs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.purchase_orders (
  id text NOT NULL,
  memo_no text NOT NULL,
  project text,
  item_name text NOT NULL,
  ordered_qty integer DEFAULT 1,
  arrived_qty integer DEFAULT 0,
  status text DEFAULT 'ordered'::text,
  note text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by text,
  updated_by text,
  audit_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budget_pools (
  id text NOT NULL,
  project text NOT NULL,
  name text NOT NULL,
  budget numeric NOT NULL DEFAULT 0,
  year text NOT NULL,
  start_month text,
  end_month text,
  memo_types ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by text,
  updated_by text,
  CONSTRAINT budget_pools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  full_name text NOT NULL UNIQUE,
  title text NOT NULL,
  name_aliases ARRAY DEFAULT '{}'::text[],
  is_approver boolean DEFAULT false,
  is_pmo boolean DEFAULT false,
  email text,
  auth_user_id uuid,
  note text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  can_review boolean NOT NULL DEFAULT false,
  can_approve boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.authority_limits (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  title text NOT NULL,
  memo_type text NOT NULL CHECK (memo_type = ANY (ARRAY['sl'::text, 'hw'::text, 'int'::text, 'ent'::text, 'dep'::text])),
  limit_thb bigint NOT NULL DEFAULT 0,
  CONSTRAINT authority_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budget_manual_expenses (
  id text NOT NULL,
  entry_kind text NOT NULL DEFAULT 'historical'::text CHECK (entry_kind = ANY (ARRAY['historical'::text, 'adjustment'::text, 'other'::text])),
  reference_no text,
  project text NOT NULL,
  budget_pool_id text,
  expense_type text NOT NULL CHECK (expense_type = ANY (ARRAY['sl'::text, 'hw'::text, 'int'::text, 'ent'::text, 'dep'::text, 'infra'::text, 'other'::text])),
  description text NOT NULL,
  frequency text NOT NULL DEFAULT 'one_time'::text CHECK (frequency = ANY (ARRAY['one_time'::text, 'monthly'::text])),
  expense_date date,
  start_month text,
  end_month text,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_cost numeric NOT NULL DEFAULT 0 CHECK (unit_cost >= 0::numeric),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  notes text,
  created_by text,
  updated_by text,
  voided_at timestamp with time zone,
  voided_by text,
  void_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  vendor_program text,
  CONSTRAINT budget_manual_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT budget_manual_expenses_budget_pool_id_fkey FOREIGN KEY (budget_pool_id) REFERENCES public.budget_pools(id)
);
